services:

    # Database Connection
    mongodb:
        container_name: mongodb
        image: mongodb/mongodb-community-server:latest
        ports:
            - 27017:27017
        networks:
            - cloud_net
        volumes:
            - cloud_vol:/data/db

    database:
        container_name: database
        restart: always
        build:
            context: database/Msi.Cad.Database
            dockerfile: Msi.Cad.Database/database.Dockerfile
        depends_on:
            - mongodb
        ports:
            - 8080:8080
        networks:
            - cloud_net
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/var/lib/application_default_credentials.json
            - GOOGLE_SERVICE_ACCOUNT_SECRET=/var/lib/msi-cad-vw-private-key.json
        volumes:
            - /home/maren/.config/gcloud:/var/lib

    # Frontend
    frontend:
        container_name: frontend
        restart: always
        build:
            context: frontend-main/
            # dockerfile: frontend.Dockerfile
            dockerfile: frontend_with_build.Dockerfile 
            args:
                REACT_APP_SERVER_ADDRESS: "http://localhost:8080"
        ports:
            - 80:80
        networks:
            - cloud_net

networks:
    cloud_net:

volumes:
    cloud_vol:
